In [182]:
import pandas as pd

In [183]:
import numpy as np

In [184]:
data= pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\raw_students.csv")

In [185]:
data

   StudentID          Name     Age  Gender  Score                Email
0          1      John doe      20    male   85.0     john@example.com
1          2   Jane Smith       19  Female   90.0  janesmith@email.com
2          3   Bob Johnson     NaN    Male   78.0       bobj@email.com
3          4   Alice Brown      21  Female    NaN      alice@email.com
4          5     Chris Lee  twenty    Male   88.0          chris@email
5          6      John Doe      20    Male   85.0     john@example.com
6          7           NaN      22  Female   92.0      sarah@email.com
7          8  Michael King      23    Male   75.0    michael@email.com

In [186]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  8 non-null      int64
 1   Name       7 non-null      object
 2   Age        7 non-null      object
 3   Gender     8 non-null      object
 4   Score      7 non-null      float64
 5   Email      8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

In [187]:
data.dtypes
data

   StudentID          Name     Age  Gender  Score                Email
0          1      John doe      20    male   85.0     john@example.com
1          2   Jane Smith       19  Female   90.0  janesmith@email.com
2          3   Bob Johnson     NaN    Male   78.0       bobj@email.com
3          4   Alice Brown      21  Female    NaN      alice@email.com
4          5     Chris Lee  twenty    Male   88.0          chris@email
5          6      John Doe      20    Male   85.0     john@example.com
6          7           NaN      22  Female   92.0      sarah@email.com
7          8  Michael King      23    Male   75.0    michael@email.com

In [188]:
data.dtypes

StudentID      int64
Name          object
Age           object
Gender        object
Score        float64
Email         object
dtype: object

In [189]:
data["Age"]=pd.to_numeric(data["Age"],errors="coerce")

In [190]:
data.dtypes

StudentID      int64
Name          object
Age          float64
Gender        object
Score        float64
Email         object
dtype: object

In [191]:
data

   StudentID          Name   Age  Gender  Score                Email
0          1      John doe  20.0    male   85.0     john@example.com
1          2   Jane Smith   19.0  Female   90.0  janesmith@email.com
2          3   Bob Johnson   NaN    Male   78.0       bobj@email.com
3          4   Alice Brown  21.0  Female    NaN      alice@email.com
4          5     Chris Lee   NaN    Male   88.0          chris@email
5          6      John Doe  20.0    Male   85.0     john@example.com
6          7           NaN  22.0  Female   92.0      sarah@email.com
7          8  Michael King  23.0    Male   75.0    michael@email.com

In [192]:
df.isnull().sum()

StudentID    0
Name         1
Age          1
Gender       0
Score        1
Email        0
dtype: int64

In [193]:
data["Age"]=data["Age"].fillna(data["Age"].mean())

In [194]:
data

   StudentID          Name        Age  Gender  Score                Email
0          1      John doe  20.000000    male   85.0     john@example.com
1          2   Jane Smith   19.000000  Female   90.0  janesmith@email.com
2          3   Bob Johnson  20.833333    Male   78.0       bobj@email.com
3          4   Alice Brown  21.000000  Female    NaN      alice@email.com
4          5     Chris Lee  20.833333    Male   88.0          chris@email
5          6      John Doe  20.000000    Male   85.0     john@example.com
6          7           NaN  22.000000  Female   92.0      sarah@email.com
7          8  Michael King  23.000000    Male   75.0    michael@email.com

In [195]:
data["Score"]=data["Score"].fillna(data["Score"].median())

In [196]:
data

   StudentID          Name        Age  Gender  Score                Email
0          1      John doe  20.000000    male   85.0     john@example.com
1          2   Jane Smith   19.000000  Female   90.0  janesmith@email.com
2          3   Bob Johnson  20.833333    Male   78.0       bobj@email.com
3          4   Alice Brown  21.000000  Female   85.0      alice@email.com
4          5     Chris Lee  20.833333    Male   88.0          chris@email
5          6      John Doe  20.000000    Male   85.0     john@example.com
6          7           NaN  22.000000  Female   92.0      sarah@email.com
7          8  Michael King  23.000000    Male   75.0    michael@email.com

In [197]:
data["Name"]=data["Name"].fillna("unknown")

In [198]:
data

   StudentID          Name        Age  Gender  Score                Email
0          1      John doe  20.000000    male   85.0     john@example.com
1          2   Jane Smith   19.000000  Female   90.0  janesmith@email.com
2          3   Bob Johnson  20.833333    Male   78.0       bobj@email.com
3          4   Alice Brown  21.000000  Female   85.0      alice@email.com
4          5     Chris Lee  20.833333    Male   88.0          chris@email
5          6      John Doe  20.000000    Male   85.0     john@example.com
6          7       unknown  22.000000  Female   92.0      sarah@email.com
7          8  Michael King  23.000000    Male   75.0    michael@email.com

In [199]:
data["Score"]=data["Score"].astype("int")

In [200]:
data

   StudentID          Name        Age  Gender  Score                Email
0          1      John doe  20.000000    male     85     john@example.com
1          2   Jane Smith   19.000000  Female     90  janesmith@email.com
2          3   Bob Johnson  20.833333    Male     78       bobj@email.com
3          4   Alice Brown  21.000000  Female     85      alice@email.com
4          5     Chris Lee  20.833333    Male     88          chris@email
5          6      John Doe  20.000000    Male     85     john@example.com
6          7       unknown  22.000000  Female     92      sarah@email.com
7          8  Michael King  23.000000    Male     75    michael@email.com

In [201]:
data["Age"]=data["Age"].astype("int")

In [202]:
data

   StudentID          Name  Age  Gender  Score                Email
0          1      John doe   20    male     85     john@example.com
1          2   Jane Smith    19  Female     90  janesmith@email.com
2          3   Bob Johnson   20    Male     78       bobj@email.com
3          4   Alice Brown   21  Female     85      alice@email.com
4          5     Chris Lee   20    Male     88          chris@email
5          6      John Doe   20    Male     85     john@example.com
6          7       unknown   22  Female     92      sarah@email.com
7          8  Michael King   23    Male     75    michael@email.com

In [203]:
data

   StudentID          Name  Age  Gender  Score                Email
0          1      John doe   20    male     85     john@example.com
1          2   Jane Smith    19  Female     90  janesmith@email.com
2          3   Bob Johnson   20    Male     78       bobj@email.com
3          4   Alice Brown   21  Female     85      alice@email.com
4          5     Chris Lee   20    Male     88          chris@email
5          6      John Doe   20    Male     85     john@example.com
6          7       unknown   22  Female     92      sarah@email.com
7          8  Michael King   23    Male     75    michael@email.com

In [204]:
data["Gender"]=data["Gender"].str.capitalize()

In [205]:
data

   StudentID          Name  Age  Gender  Score                Email
0          1      John doe   20    Male     85     john@example.com
1          2   Jane Smith    19  Female     90  janesmith@email.com
2          3   Bob Johnson   20    Male     78       bobj@email.com
3          4   Alice Brown   21  Female     85      alice@email.com
4          5     Chris Lee   20    Male     88          chris@email
5          6      John Doe   20    Male     85     john@example.com
6          7       unknown   22  Female     92      sarah@email.com
7          8  Michael King   23    Male     75    michael@email.com

In [206]:
data["Name"]=data["Name"].str.title()

In [207]:
data

   StudentID          Name  Age  Gender  Score                Email
0          1      John Doe   20    Male     85     john@example.com
1          2   Jane Smith    19  Female     90  janesmith@email.com
2          3   Bob Johnson   20    Male     78       bobj@email.com
3          4   Alice Brown   21  Female     85      alice@email.com
4          5     Chris Lee   20    Male     88          chris@email
5          6      John Doe   20    Male     85     john@example.com
6          7       Unknown   22  Female     92      sarah@email.com
7          8  Michael King   23    Male     75    michael@email.com

In [208]:
data

   StudentID          Name  Age  Gender  Score                Email
0          1      John Doe   20    Male     85     john@example.com
1          2   Jane Smith    19  Female     90  janesmith@email.com
2          3   Bob Johnson   20    Male     78       bobj@email.com
3          4   Alice Brown   21  Female     85      alice@email.com
4          5     Chris Lee   20    Male     88          chris@email
5          6      John Doe   20    Male     85     john@example.com
6          7       Unknown   22  Female     92      sarah@email.com
7          8  Michael King   23    Male     75    michael@email.com

In [209]:
data=data.iloc[:,1:]

In [210]:
b=data.copy()

In [211]:
b.head(10)

           Name  Age  Gender  Score                Email
0      John Doe   20    Male     85     john@example.com
1   Jane Smith    19  Female     90  janesmith@email.com
2   Bob Johnson   20    Male     78       bobj@email.com
3   Alice Brown   21  Female     85      alice@email.com
4     Chris Lee   20    Male     88          chris@email
5      John Doe   20    Male     85     john@example.com
6       Unknown   22  Female     92      sarah@email.com
7  Michael King   23    Male     75    michael@email.com

In [212]:
b.drop_duplicates()

           Name  Age  Gender  Score                Email
0      John Doe   20    Male     85     john@example.com
1   Jane Smith    19  Female     90  janesmith@email.com
2   Bob Johnson   20    Male     78       bobj@email.com
3   Alice Brown   21  Female     85      alice@email.com
4     Chris Lee   20    Male     88          chris@email
6       Unknown   22  Female     92      sarah@email.com
7  Michael King   23    Male     75    michael@email.com

In [213]:
b.drop_duplicates(inplace=True)

In [214]:
data.loc[4, "Email"] = data.loc[4, "Email"] + ".com"

In [215]:
data

           Name  Age  Gender  Score                Email
0      John Doe   20    Male     85     john@example.com
1   Jane Smith    19  Female     90  janesmith@email.com
2   Bob Johnson   20    Male     78       bobj@email.com
3   Alice Brown   21  Female     85      alice@email.com
4     Chris Lee   20    Male     88      chris@email.com
5      John Doe   20    Male     85     john@example.com
6       Unknown   22  Female     92      sarah@email.com
7  Michael King   23    Male     75    michael@email.com