In [2]:
import numpy as np
import pandas as pd

In [5]:
pd.Series([1,2,3,4,5])#default it took values from 0,1,2,3,4

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"]) #here, we are specifiying index values

In [7]:
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
data.shape

(5,)

In [9]:
data.values

array([1, 2, 3, 4, 5], dtype=int64)

In [12]:
data["a"]

1

In [13]:
data["e"]

5

In [15]:
data.iloc[2]

3

In [20]:
data.iloc[1], data.loc["a"]

(2, 1)

In [21]:
data.loc[["a","c","e"]],data.iloc[3]

(a    1
 c    3
 e    5
 dtype: int64,
 4)

In [22]:
data={
    "name":["kruthika", "suraj","acchu"],
    "usn":[1,2,3],
    "branch":["cs","mca","AI"]
}

In [23]:
df=pd.DataFrame(data)
df

       name  usn branch
0  kruthika    1     cs
1     suraj    2    mca
2     acchu    3     AI

In [27]:
data=pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\sample.csv")
data

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,1/15/2021,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,3/10/2019,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,7/22/2020,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,9/30/2015,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,6/12/2018,Mumbai,4.1
5,5,106,John,Finance,29,58000,3,11/5/2021,Delhi,3.9
6,6,107,Meena,IT,41,82000,15,4/18/2010,Bangalore,4.8
7,7,108,David,HR,26,48000,2,2/14/2022,Mumbai,3.7
8,8,109,Sara,Finance,38,61000,12,12/1/2013,Delhi,4.3
9,9,110,Arjun,IT,27,54000,4,8/19/2020,Bangalore,4.0
10,10,111,Ravi,HR,33,47000,6,5/23/2017,Mumbai,3.6
11,11,112,Priya,Finance,31,59000,5,9/17/2019,Delhi,4.4
12,12,113,Kunal,IT,45,90000,18,3/11/2008,Bangalore,4.9
13,13,114,Sneha,HR,29,51000,3,7/29/2021,Mumbai,3.5
14,14,115,Vijay,Finance,36,62000,11,1/10/2014,Delhi,4.2
15,15,116,Neha,IT,40,88000,14,10/21/2011,Bangalore,4.7
16,16,117,Amit,HR,34,53000,8,4/5/2016,Mumbai,4.0
17,17,118,Pooja,Finance,30,57000,6,12/12/2018,Delhi,4.1
18,18,119,Rahul,IT,28,56000,4,2/28/2020,Bangalore,3.9
19,19,120,Divya,HR,37,49500,9,6/30/2015,Mumbai,4.3

In [28]:
data.head()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,1/15/2021,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,3/10/2019,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,7/22/2020,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,9/30/2015,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,6/12/2018,Mumbai,4.1

In [29]:
data.head(10)

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
0,0,101,Ram,IT,25,50000,2,1/15/2021,Bangalore,4.5
1,1,102,Shyam,HR,30,45000,5,3/10/2019,Mumbai,3.8
2,2,103,Geeta,Finance,28,60000,4,7/22/2020,Delhi,4.2
3,3,104,Anita,IT,35,75000,10,9/30/2015,Bangalore,4.9
4,4,105,Kiran,HR,32,52000,7,6/12/2018,Mumbai,4.1
5,5,106,John,Finance,29,58000,3,11/5/2021,Delhi,3.9
6,6,107,Meena,IT,41,82000,15,4/18/2010,Bangalore,4.8
7,7,108,David,HR,26,48000,2,2/14/2022,Mumbai,3.7
8,8,109,Sara,Finance,38,61000,12,12/1/2013,Delhi,4.3
9,9,110,Arjun,IT,27,54000,4,8/19/2020,Bangalore,4.0

In [30]:
data.describe()

,Unnamed: 0,EmpID,Age,Salary,Experience,PerformanceScore
count,20.00000,20.00000,20.000000,20.000000,20.000000,20.000000
mean,9.50000,110.50000,32.700000,59875.000000,7.400000,4.190000
std,5.91608,5.91608,5.449288,13388.796377,4.615762,0.415363
min,0.00000,101.00000,25.000000,45000.000000,2.000000,3.500000
25%,4.75000,105.75000,28.750000,50750.000000,4.000000,3.900000
50%,9.50000,110.50000,31.500000,56500.000000,6.000000,4.150000
75%,14.25000,115.25000,36.250000,61250.000000,10.250000,4.425000
max,19.00000,120.00000,45.000000,90000.000000,18.000000,4.900000

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        20 non-null     int64
 1   EmpID             20 non-null     int64
 2   Name              20 non-null     object
 3   Department        20 non-null     object
 4   Age               20 non-null     int64
 5   Salary            20 non-null     int64
 6   Experience        20 non-null     int64
 7   JoiningDate       20 non-null     object
 8   City              20 non-null     object
 9   PerformanceScore  20 non-null     float64
dtypes: float64(1), int64(5), object(4)
memory usage: 1.7+ KB

In [32]:
data.sample()

,Unnamed: 0,EmpID,Name,Department,Age,Salary,Experience,JoiningDate,City,PerformanceScore
18,18,119,Rahul,IT,28,56000,4,2/28/2020,Bangalore,3.9

In [35]:
data.shape

(20, 10)

In [37]:
data.Name

0       Ram
1     Shyam
2     Geeta
3     Anita
4     Kiran
5      John
6     Meena
7     David
8      Sara
9     Arjun
10     Ravi
11    Priya
12    Kunal
13    Sneha
14    Vijay
15     Neha
16     Amit
17    Pooja
18    Rahul
19    Divya
Name: Name, dtype: object

In [40]:
data[["Name","Department","Salary"]]

     Name Department  Salary
0     Ram         IT   50000
1   Shyam         HR   45000
2   Geeta    Finance   60000
3   Anita         IT   75000
4   Kiran         HR   52000
5    John    Finance   58000
6   Meena         IT   82000
7   David         HR   48000
8    Sara    Finance   61000
9   Arjun         IT   54000
10   Ravi         HR   47000
11  Priya    Finance   59000
12  Kunal         IT   90000
13  Sneha         HR   51000
14  Vijay    Finance   62000
15   Neha         IT   88000
16   Amit         HR   53000
17  Pooja    Finance   57000
18  Rahul         IT   56000
19  Divya         HR   49500

In [42]:
type(data.Name)

pandas.core.series.Series

In [78]:
data=pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\test2.csv")
data

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [44]:
data.isnull().sum()

Unnamed: 0    0
Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [45]:
data.isnull()

   Unnamed: 0   Name    Age  Department  Salary
0       False  False  False       False   False
1       False  False  False       False   False
2       False  False  False       False   False
3       False  False   True       False   False
4       False  False  False       False    True
5       False  False  False       False   False

In [50]:
data.loc[ :, "Name":"Department"]

      Name   Age Department
0    Alice  25.0         HR
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT
4      Eve  29.0         HR
5    Alice  25.0         HR

In [51]:
data.loc["0" :"1","Name":"Department"]

    Name   Age Department
0  Alice  25.0         HR
1    Bob  30.0         IT

In [52]:
data.loc["1":"3","Name":"Department"] #works on labels, include function

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [53]:
data.iloc[1:4,1:4]#works on location,Exclude function

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [57]:
data.rename(columns={"Name":"fname","Age":"A","Department":"D","Salary":"S"})# it stores temporory

   Unnamed: 0    fname     A        D        S
0           0    Alice  25.0       HR  50000.0
1           1      Bob  30.0       IT  60000.0
2           2  Charlie  35.0  Finance  70000.0
3           3    David   NaN       IT  62000.0
4           4      Eve  29.0       HR      NaN
5           5    Alice  25.0       HR  50000.0

In [58]:
data

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
3           3    David   NaN         IT  62000.0
4           4      Eve  29.0         HR      NaN
5           5    Alice  25.0         HR  50000.0

In [61]:
data.rename(columns={"Name":"fname","Age":"A","Department":"D","Salary":"S"},inplace=True)

In [62]:
data

   Unnamed: 0    fname     A        D        S
0           0    Alice  25.0       HR  50000.0
1           1      Bob  30.0       IT  60000.0
2           2  Charlie  35.0  Finance  70000.0
3           3    David   NaN       IT  62000.0
4           4      Eve  29.0       HR      NaN
5           5    Alice  25.0       HR  50000.0

In [65]:
data.drop('Unnamed: 0',axis=1,inplace=True) #axis=1 means remove rows  #axis=0 means for columns

In [66]:
data

     fname     A        D        S
0    Alice  25.0       HR  50000.0
1      Bob  30.0       IT  60000.0
2  Charlie  35.0  Finance  70000.0
3    David   NaN       IT  62000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  50000.0

In [70]:
data["updated_salary"]=data["S"]+5000

In [71]:
data

     fname     A        D        S  updated_salary
0    Alice  25.0       HR  50000.0         55000.0
1      Bob  30.0       IT  60000.0         65000.0
2  Charlie  35.0  Finance  70000.0         75000.0
3    David   NaN       IT  62000.0         67000.0
4      Eve  29.0       HR      NaN             NaN
5    Alice  25.0       HR  50000.0         55000.0

In [74]:
data["updated_salary2"]=data["S"].map(lambda x:x+1000)

In [73]:
data

     fname     A        D        S  updated_salary  updated_salary2
0    Alice  25.0       HR  50000.0         55000.0          60000.0
1      Bob  30.0       IT  60000.0         65000.0          70000.0
2  Charlie  35.0  Finance  70000.0         75000.0          80000.0
3    David   NaN       IT  62000.0         67000.0          72000.0
4      Eve  29.0       HR      NaN             NaN              NaN
5    Alice  25.0       HR  50000.0         55000.0          60000.0

In [76]:
data.A

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: A, dtype: float64

In [77]:
data[data["A"]>25]

     fname     A        D        S  updated_salary  updated_salary2
1      Bob  30.0       IT  60000.0         65000.0          61000.0
2  Charlie  35.0  Finance  70000.0         75000.0          71000.0
4      Eve  29.0       HR      NaN             NaN              NaN

In [79]:
data.dropna(inplace=True) #remove the null values

In [80]:
data

   Unnamed: 0     Name   Age Department   Salary
0           0    Alice  25.0         HR  50000.0
1           1      Bob  30.0         IT  60000.0
2           2  Charlie  35.0    Finance  70000.0
5           5    Alice  25.0         HR  50000.0

In [81]:
data.isnull().sum() #converting it to the integer values

Unnamed: 0    0
Name          0
Age           0
Department    0
Salary        0
dtype: int64

In [1]:
import pandas as pd

# Create the Series with custom labels
products = pd.Series(
    data=[700, 150, 300],
    index=['Laptop', 'Mouse', 'Keyboard']
)

# Access price of 'Laptop' using label-based indexing
laptop_price = products['Laptop']

# Slice the first two products using positional indexing
first_two_products = products.iloc[:2]

# Output
print("Full Products Series:")
print(products)

print("\nPrice of Laptop:")
print(laptop_price)

print("\nFirst two products (positional slicing):")
print(first_two_products)

Full Products Series:
Laptop      700
Mouse       150
Keyboard    300
dtype: int64

Price of Laptop:
700

First two products (positional slicing):
Laptop    700
Mouse     150
dtype: int64

In [2]:
import pandas as pd

# Create the Series with missing values
grades = pd.Series([85, None, 92, 45, None, 78, 55])

# Identify missing values
missing = grades.isnull()

# Fill missing values with 0
filled_grades = grades.fillna(0)

# Apply boolean mask to filter scores > 60
passed = filled_grades[filled_grades > 60]

# Output
print("Original Grades Series:")
print(grades)

print("\nMissing Values (True = missing):")
print(missing)

print("\nFilled Grades Series (None -> 0):")
print(filled_grades)

print("\nScores Greater Than 60:")
print(passed)

Original Grades Series:
0    85.0
1     NaN
2    92.0
3    45.0
4     NaN
5    78.0
6    55.0
dtype: float64

Missing Values (True = missing):
0    False
1     True
2    False
3    False
4     True
5    False
6    False
dtype: bool

Filled Grades Series (None -> 0):
0    85.0
1     0.0
2    92.0
3    45.0
4     0.0
5    78.0
6    55.0
dtype: float64

Scores Greater Than 60:
0    85.0
2    92.0
5    78.0
dtype: float64

In [3]:
import pandas as pd

# Create the Series
usernames = pd.Series([' Alice ', 'bOB', ' Charlie_Data ', 'daisy'])

# Clean the text using vectorized string methods
cleaned = usernames.str.strip().str.lower()

# Check which names contain the letter 'a'
contains_a = cleaned.str.contains('a')

# Output
print("Original Usernames:")
print(usernames)

print("\nCleaned Usernames (stripped & lowercase):")
print(cleaned)

print("\nContains letter 'a':")
print(contains_a)

Original Usernames:
0            Alice
1               bOB
2     Charlie_Data
3             daisy
dtype: object

Cleaned Usernames (stripped & lowercase):
0           alice
1             bob
2    charlie_data
3           daisy
dtype: object

Contains letter 'a':
0     True
1    False
2     True
3     True
dtype: bool